spring.application.name=carrentalhub

spring.datasource.url=jdbc:postgresql://localhost:5432/carrental_db
spring.datasource.username=postgres
spring.datasource.password=!cindymun55
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#server.port = 8082
